### ISSUE TITLE
(Phoenix.MissingParamError) expected key for "post" to be present

### ISSUE THREAD

**Issue by ACPK** [renatomoya/rest_api#1]
When I tried the app, I get the error below:  

    Request: POST /v1/posts
    ** (exit) an exception was raised:
        ** (Phoenix.MissingParamError) expected key for "post" to be present
            (phoenix) lib/phoenix/controller.ex:563: Phoenix.Controller.scrub_params/2
            (rest_api) web/controllers/v1/post_controller.ex:1: RestApi.V1.PostController.phoenix_controller_pipeline/2
            (rest_api) lib/phoenix/router.ex:297: RestApi.Router.dispatch/2
            (rest_api) lib/phoenix/router.ex:2: RestApi.Router.call/2
            (rest_api) lib/rest_api/endpoint.ex:1: RestApi.Endpoint.phoenix_endpoint_pipeline/1
            (rest_api) lib/plug/debugger.ex:90: RestApi.Endpoint."call (overridable 3)"/2
            (rest_api) lib/phoenix/endpoint/render_errors.ex:34: RestApi.Endpoint.call/2
            (phoenix) lib/phoenix/endpoint/cowboy_handler.ex:50: Phoenix.Endpoint.CowboyHandler.upgrade/4

**Comment by zmoshansky** [comment]
The analagous solution for my own api was to post the json formatted as follows:
```
{
   "post": {
      "title": "bar",
      "content": "foo"
   }
}
```

**Comment by ACPK** [comment]
https://www.runscope.com/radar/olof82yywvhv/fbbc463c-4ee8-4b79-8100-0b04622b24b6/history/7747ee23-349a-4a16-acdb-efd6c57383f3

**Comment by zmoshansky** [comment]
Try adding a content type header: `Content-Type: application/json`. I removed it from an otherwise valid request and recieved the same error as you have. I have been using https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=en to test and it's great!

```
curl -X POST -H "Content-Type: application/json" -d '{
   "post": {
      "title": "bar",
      "content": "foo"
   }
}' http://localhost:4000/v1/posts
```

**Comment by ACPK** [comment]
@zmoshansky Wow, that was easy. Any recommendations on removing the  "post": { } so I can just pass in the two form parameters (ex: title and content)?

**Comment by zmoshansky** [comment]
@ACPK Unfortunately I just started with phoenix last week so I'm pretty green as well. Your question was the only one I could find about posting JSON as I tracked down this error, as my first intuition was not to add a `"post: {}` wrapper either. Try asking over on the phoenix repo or perhaps better stackoverflow and ping an author? IIRC Jose Valim et al. is pretty active on SO.

**Comment by urkh** [comment]
@ACPK @zmoshansky :

if you want to pass parameters in this way ```{"title":"mytitle","content":"mycontent"}```,  then they have to change your create method:

```def create (conn,% {"post" => post_params})```

to

```def create (conn, post_params)```

btw, I'm also new on elixir / phoenix :beers:

**Comment by ACPK** [comment]
@urkh  - Salud to Phoenix!

**Comment by zmoshansky** [comment]
@urkh, @ACPK  I've discovered the not so nice side effect of passing parameters as `{"title":"mytitle","content":"mycontent"}`. If you have a route like `/post/:id`, and need to put/patch to it for a request, then the id ends up getting jumbled in with all of your other parameters, including extraneous things params like `"format" => "json`.

I imagine everything is nested like for this reason, and has scrub_params: to keep it clean.

Clusterf*** of request params and phoenix params
```
%{"format" => "json", "title" => "woot", "content" => "my-list", "id"="10"}
```
vs.
```
%{"format" => "json", "id"="10", "post" => {"title" => "woot", "content" => "my-list"}}
```

**Comment by urkh** [comment]
@zmoshansky 

you're right, just now, I had the same problem you write
